/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TickerRegistry = TickerModuleInfo[];

export interface TickerModuleInfo {
	id: string;
	name: string;
	description: string;
	dialogName?: string;
	bundleName?: string;
	[k: string]: unknown;
}
